version: '3'
services:
  jupyter:
    build: .
    working_dir: /workdir
    command: sleep infinity
    volumes:
      - ~/.gitconfig:/home/root/.gitconfig:ro
      - ..:/workdir
    environment:
      - JUPYTER_ENABLE_LAB=yes
