version: '3'
services:
  jupyter:
    build: .
    working_dir: /workdir
    command: sleep infinity
    volumes:
      - ~/.gitconfig:/home/root/.gitconfig:ro
      - ..:/workdir
    # ports:
    #   - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    # command: jupyter lab --allow-root --no-browser --port=8888 --ip=* --NotebookApp.token=''
